Vagrant.configure("2") do |config|

  config.vm.define "monitoring" do |monitoring|
    monitoring.vm.box = "bento/centos-7.5"
    monitoring.vm.provider :virtualbox do |p|
      monitoring.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
      monitoring.vm.network "forwarded_port", guest: 443, host: 8443, host_ip: "127.0.0.1"
      monitoring.vm.network "forwarded_port", guest: 5665, host: 8665, host_ip: "127.0.0.1"
    end

    monitoring.vm.provision "chef_zero" do |chef|
      chef.cookbooks_path = "cookbooks"
      chef.nodes_path = "nodes"
      chef.run_list = [ 'recipe[unittests-monitoring::default]' ]
    end
  end

  config.vm.define "uyuni" do |uyuni|
    uyuni.vm.box = "generic/opensuse42"
    uyuni.vm.network "forwarded_port", guest: 80, host: 8081
    uyuni.vm.network "forwarded_port", guest: 443, host: 8444
    uyuni.vm.provider "virtualbox" do |vb|
      vb.memory = "4096"
    end
    uyuni.vm.provision "chef_zero" do |chef|
      chef.cookbooks_path = "cookbooks"
      chef.nodes_path = "nodes"
      chef.run_list = [ 'recipe[uyuni-basic::default]' ]
    end
  end
end
